### ISSUE TITLE
Support for toolranks mod in minetest-game/farming is a wontfix

### ISSUE THREAD

**Issue by louisroyer** [lisacvuk/minetest-toolranks#10]
See minetest/minetest_game/pull/2592.
In my opinion, we should implements directly hoes here because farming is also part of minetest-game. If we ask [farming redo](https://notabug.org/TenPlus1/farming) to remove toolranks support and if we add farming support, I think it would be ok (and if farming redo adds more hoes in the future, we could still detect they are from this mod with `farming.mod` they define), no circular dependency.
I think it is sad to not have toolranks on hoes when not using farming redo…

**Comment by louisroyer** [comment]
An other solution could be the creation of a mod (lets say `toolranks-extras`) adding support for hoes using your API, while `toolranks` will only provide support for `default`’s tools (and an API). This would also avoid circular dependencies but this is less intuitive for users.

**Comment by lisacvuk** [comment]
Honestly i feel this isn't something we need to address; subgame creators can manually support toolranks, as well as mod creators. Default farming mod isn't really important imo

**Comment by louisroyer** [comment]
Ok. If someone else needs it, I have implemented [the mod I was talking about](https://github.com/louisroyer/minetest-toolranks-extras) to meet my personal needs.
