### ISSUE TITLE
crash trying to mention nssm-provided `:farming:ant_hoe`'s description

### ISSUE THREAD

**Issue by nonchip** [lisacvuk/minetest-toolranks#16]
nssm [declares](https://notabug.org/TenPlus1/nssm/src/master/nssm_materials.lua#L658) a `:farming:ant_hoe`, with a `description`.

farming redo [calls upon](https://notabug.org/TenPlus1/farming/src/master/hoes.lua#L127) toolranks to notify it of hoe usage.

trying to e.g. level one of those up by using them, or, in this case, showing the "this item is the most used ever now!" message, crashes the game with (exact line in `toolranks/init.lua` depends on which message was shown, e.g. if it didn't become the most used it crashes on trying to update the tooltip):
```
ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnUse(): ...rc/minetest-5.3.0/bin/../builtin/common/misc_helpers.lua:623: attempt to concatenate a nil value
stack traceback:
       ...rc/minetest-5.3.0/bin/../builtin/common/misc_helpers.lua:623: in function <...rc/minetest-5.3.0/bin/../builtin/common/misc_helpers.lua:610>
       [C]: in function 'gsub'
       ...rc/minetest-5.3.0/bin/../builtin/common/misc_helpers.lua:610: in function 'S'
       ...mes/worst_block_game_mt/mods/minetest-toolranks/init.lua:79: in function 'new_afteruse'
       ...minetest/games/worst_block_game_mt/mods/farming/hoes.lua:127: in function <...minetest/games/worst_block_game_mt/mods/farming/hoes.lua:62>
```

adding some debug `print`s myself, i figured out that `itemdesc` (and, by extension, `itemdef.original_description`) appears to be `nil`, even tho the `description` field when registering the item was clearly not (and i can see its original name in the tooltip, without any "level 0" fancyness from toolranks, like maybe it never got initialized? nssm does *not* depend on toolranks, but on `farming?`, which depends on `toolranks?`, and manually adding it to nssm's dependencies did change nothing).

**Comment by nonchip** [comment]
ok, this seems to have been a bug with farming redo, i found and (temporarily) fixed it, will report with them.
essentially since they're calling `new_afteruse` directly instead of registering the tool with toolranks, the `original_description` was never set.

**Comment by nonchip** [comment]
actually was a bug with nssm *and* farming redo in combination due to how farming redo implements toolranks support (badly, by hardcoding the default materials, instead of checking add_hoe)

**Comment by lisacvuk** [comment]
ah I see, glad you solved it :)

**Comment by nonchip** [comment]
well, if you wanna call [this](https://gitlab.com/worstconcept/worstblockgame/-/blob/master/mods/wbg_modcompat/init.moon#L12) a solution ;)

thing is, if i go to farming redo and ask them to fix it, that'd break any other mod that relies on their ugly solution, and nssm literally doesn't even try to support toolranks at all (which is why farming redo fails because it assumes all hoes to be ranked if toolranks is installed), so my "compatibility layer" gluing them together seems like the least worst option.

**Comment by louisroyer** [comment]
> thing is, if i go to farming redo and ask them to fix it, that'd break any other mod that relies on their ugly solution, and nssm literally doesn't even try to support toolranks at all (which is why farming redo fails because it assumes all hoes to be ranked if toolranks is installed), so my "compatibility layer" gluing them together seems like the least worst option.

@nonchip 
A patch for [farming redo](https://notabug.org/TenPlus1/farming/src/master/hoes.lua#L126):
```diff
-	if tr then
+	local itemdef = itemstack:get_definition()
+	local after_use = itemdef.after_use
+	if after_use then
+		after_use(itemstack, user, under, {wear = wear})
+	elseif tr and itemdef.original_description then
		itemstack = toolranks.new_afteruse(itemstack, user, under, {wear = wear})
	else
		itemstack:add_wear(wear)
	end
```
I have not tested the above code yet (so you might have some adjustments to do), but it should allow you to register your hoes as other tools while preserving compatibility with everything. If it works, please transmit it to TenPlus1 (and keep me up, so I can test my mods's compatibility with yours :smile:).
