### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by dacmot** [lisacvuk/minetest-toolranks#19]
Since the source code has no license, it is assumed to be closed source.

Would you please add a license file? According to the minetest forum page https://forum.minetest.net/viewtopic.php?t=18056, it should be considered LGPLv2.1+. You can download a copy of the license at https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt. Also since a sound is used from another source, it should be mentioned either in the license file or the readme.

Thanks.

**Comment by lisacvuk** [comment]
Fixed 00538232daf10c7e29a5ed213e88e2accd2f7354 & 05eea5177e4c804eea6fdf77eccd141405b38613 - thank you :)

**Comment by dacmot** [comment]
Amazing! Thank you for the quick response.
