### ISSUE TITLE
Circular dependencies: toolranks -> moreores -> farming (Farming Redo) ->toolranks

### ISSUE THREAD

**Issue by Ginger88895** [lisacvuk/minetest-toolranks#5]
As described in the title; Farming Redo is done by TenPlus1.

A possible way to fix this is to make this a modpack; the API support should be named under "toolranks" (so that existing mods do not need to be change), and all the overridden tools should be placed under something similar to "toolranks_tools"...

EDIT: I will try to fix this in my branch; a pull request will be provided if I succeed.

**Comment by RicardoNoguerales** [comment]
You could try this
- Remove moreores dependency.
- Wrap moreores part inside of 
minetest.register_on_mods_loaded(function() ........ end)
This should delay execution until all mods are loaded, included moreores.

.......................................
  after_use = toolranks.new_afteruse})
minetest.register_on_mods_loaded(function()       --<----HERE
if minetest.get_modpath("moreores") then

  minetest.override_item("moreores:pick_mithril", {
    original_description = "Mithril Pickaxe",
    description = toolranks.create_description("Mithril Pickaxe", 0, 1),
    after_use = toolranks.new_afteruse})
...............................................
  minetest.override_item("moreores:sword_silver", {
    original_description = "Silver Sword",
    description = toolranks.create_description("Silver Sword", 0, 1),
    after_use = toolranks.new_afteruse})
end
end)  --<----HERE
-- add swords for snappy nodes
...............................

Hmm, using old browser.
Neither text formatting nor Preview works for me, sorry.
